// aspects.js — the frame SHAPES a video can be, and what they measure.
//
// ⚠ THE ASPECT RATIO IS A PROPERTY OF THE VIDEO, not of the screen you cut it
// on. Nothing here is a layout concern: `workspace.js` decides where the panes
// sit and is forbidden from touching this, which is why switching to the Reel
// workspace on a 16:9 animatic leaves it 16:9 until someone actually says
// otherwise. The saying-otherwise is the Program pane's picker and the Shape
// chips in Video properties — two controls, ONE field (`settings.aspect_ratio`),
// so they can never disagree about what the film is.
//
// One list, because three places used to answer the same question separately:
// the chips in `properties/VideoProperties.jsx`, the size table in
// `AnimaticEditor.jsx`, and the export dialog's "1080p — 1920×1080".

// What you can PICK. Deliberately shorter than the size table below: these are
// the shapes anyone publishes in, and a row of chips is a choice, not a
// reference. A project already set to something else keeps it — see
// `knownAspect()`.
export const ASPECTS = [
  { id: "16:9", label: "16:9", note: "Wide" },
  { id: "9:16", label: "9:16", note: "Reels" },
  { id: "1:1", label: "1:1", note: "Square" },
  { id: "4:3", label: "4:3", note: "Classic" },
  { id: "4:5", label: "4:5", note: "Portrait" },
];

// The familiar frame sizes, written for a 1080 SHORT edge and scaled from there
// — the same rule `resolve_size()` uses on the server, so a dialog can show the
// real output size before anything is encoded. Keep the two in step.
//
// Wider than `ASPECTS` on purpose: a board generated by the storyboard workflow
// can arrive as 3:4 or 21:9, and it must still be measured exactly rather than
// derived. Anything not listed is derived from the ratio, both here and on the
// server, so an unknown shape exports correctly — it just isn't a chip.
export const BASE_SIZES = {
  "16:9": [1920, 1080],
  "9:16": [1080, 1920],
  "1:1": [1080, 1080],
  "4:3": [1440, 1080],
  "3:4": [1080, 1440],
  "4:5": [1080, 1350],
  "21:9": [1920, 824],
};

const even = (n) => (Math.round(n) % 2 === 0 ? Math.round(n) : Math.round(n) + 1);

// "16:9" → 1.777…, for the CSS that has to hold the monitor's shape. Falls back
// to 16:9 on anything unparseable rather than returning NaN and collapsing the
// preview to nothing.
export function aspectNumber(aspect) {
  const [w, h] = String(aspect || "16:9")
    .split(":")
    .map(Number);
  return w > 0 && h > 0 ? w / h : 16 / 9;
}

// The LONG edge an unlisted ratio is derived from. ⚠ The long one, matching
// `_base_size` in animatic.py — deriving off the SHORT edge instead is a
// perfectly reasonable rule that makes 5:2 come out 2700×1080 here and
// 1920×768 there, which is a dialog quoting a size the encoder will not write.
const LONG_EDGE = 1920;

// The pixel size an export at this shape and this SHORT edge comes out as.
// ⚠ TWIN of `resolve_size()` in animatic.py, table and fallback both.
export function frameSizeFor(aspect, resolution) {
  const scale = (resolution || 1080) / 1080;
  const base = BASE_SIZES[aspect] || derivedSize(aspect);
  return [even(base[0] * scale), even(base[1] * scale)];
}

// Unlisted but parseable — the long edge is 1920 and the other side follows.
function derivedSize(aspect) {
  const n = aspectNumber(aspect);
  return n >= 1 ? [even(LONG_EDGE), even(LONG_EDGE / n)] : [even(LONG_EDGE * n), even(LONG_EDGE)];
}

// Is this shape one of the chips? A project can hold a shape nobody can pick —
// see `BASE_SIZES` — and a picker that silently showed it as 16:9 would be
// lying about the film. Callers offer the real value as an extra option.
export function knownAspect(aspect) {
  return ASPECTS.some((a) => a.id === aspect);
}

// A frame's pixel size in SHORT-EDGE units — the short edge is 1, whichever one
// it is. The same rule `resolve_size()` scales by, which is what makes "1080p"
// mean 1920×1080 wide and 1080×1920 tall.
function frameUnits(aspect) {
  const n = aspectNumber(aspect);
  return n >= 1 ? [n, 1] : [1, 1 / n];
}

/**
 * A box (a shape, an overlay) carried from one frame shape to another.
 *
 * ⚠ WHY THIS HAS TO EXIST. A shape's `w`/`h` are fractions of the FRAME's width
 * and height — that is the model, here and in `draw_shapes` on the server — so
 * the same two numbers describe a different rectangle in a different frame. Go
 * 16:9 → 9:16 and a square star becomes a tall lozenge, having been told
 * nothing and asked nothing. The pictures don't have this problem because
 * `placePicture` re-fits them from the source every draw; a shape has no source
 * to re-fit from, so the numbers themselves have to be carried over.
 *
 * What is preserved is the box's PROPORTION and its apparent SIZE: both frames
 * are measured against their short edge, which is exactly what the exporter
 * does, so a star keeps its shape and its pixels and only the frame around it
 * changes. It round-trips — 16:9 → 9:16 → 16:9 gives back the numbers you
 * started with — so flipping between shapes to compare them costs nothing.
 *
 * The one lossy case is a box that no longer fits: something nearly as wide as
 * a 16:9 frame is wider than a 9:16 frame *is*. It is scaled down whole rather
 * than cropped, because half a star off the edge is not a smaller star.
 */
export function refitBox(box, from, to) {
  const [fromW, fromH] = frameUnits(from);
  const [toW, toH] = frameUnits(to);
  let w = (Math.abs(Number(box.w ?? 0.25)) * fromW) / toW;
  let h = (Math.abs(Number(box.h ?? 0.25)) * fromH) / toH;
  const over = Math.max(w, h, 1);
  if (over > 1) {
    w /= over;
    h /= over;
  }
  // Six places: enough that a round trip is exact to the pixel at 4K, short
  // enough that the saved document doesn't fill with float noise.
  const round = (v) => Math.round(v * 1e6) / 1e6;
  return { w: round(w), h: round(h) };
}
