"""Write the built-in .cube files. Run it, commit the result.

The LUTs are FILES, not code, on purpose: `animatic_effects.py` reads them with
`PIL.ImageFilter.Color3DLUT` and the browser reads the same bytes into a texture
in `client/src/animatic/gl/lut.js`. One artefact, two readers — which is the
opposite of the mistake `_SHAPE_POINTS` made, where the same numbers were typed
into two files and have been drifting ever since.

    python luts/generate_luts.py

SIZE 9, deliberately. Every look below is a smooth monotone curve, so 9 grid
points reconstruct it under trilinear interpolation to well inside the parity
tolerance, and the file stays ~15KB — which matters because the browser
downloads it before it can grade a frame. Add a look with a hard break in it and
raise the size for that one file; the parser reads whatever LUT_3D_SIZE says.

⚠ `identity.cube` is not decoration. It is the fixture `tests/effects_check.py`
uses to prove a LUT round-trips to the picture it was given — the one test that
catches the classic .cube bug of reading the table with blue changing fastest
instead of red.
"""

import os

SIZE = 9
HERE = os.path.dirname(os.path.abspath(__file__))


def _clamp(v: float) -> float:
    return 0.0 if v < 0 else (1.0 if v > 1 else v)


def _lift_gamma(c: float, gamma: float) -> float:
    return _clamp(c) ** gamma


def identity(r, g, b):
    return r, g, b


def warm(r, g, b):
    """Golden hour: reds opened up, blues pulled down, a touch of contrast."""
    return (
        _lift_gamma(r, 0.88),
        _lift_gamma(g, 0.96),
        _lift_gamma(b, 1.15),
    )


def cool(r, g, b):
    """Night / moonlight: the same curve the other way round."""
    return (
        _lift_gamma(r, 1.15),
        _lift_gamma(g, 1.02),
        _lift_gamma(b, 0.86),
    )


def noir(r, g, b):
    """Black and white with the contrast pushed. ITU-R 601 luma, as everywhere."""
    y = 0.299 * r + 0.587 * g + 0.114 * b
    y = _clamp((y - 0.5) * 1.25 + 0.5)
    return y, y, y


def teal_orange(r, g, b):
    """The blockbuster grade: shadows toward teal, highlights toward orange."""
    y = 0.299 * r + 0.587 * g + 0.114 * b
    return (
        _clamp(r + 0.10 * (y - 0.5)),
        _clamp(g + 0.02 * (y - 0.5)),
        _clamp(b - 0.12 * (y - 0.5)),
    )


LOOKS = {
    "identity": identity,
    "warm": warm,
    "cool": cool,
    "noir": noir,
    "teal_orange": teal_orange,
}


def write_cube(name: str, fn) -> str:
    lines = [
        f"# {name} — generated by luts/generate_luts.py. Do not edit by hand.",
        f'TITLE "{name}"',
        f"LUT_3D_SIZE {SIZE}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
        "",
    ]
    # ⚠ RED CHANGES FASTEST. That is the .cube format's order and the single
    # easiest thing to get backwards — an identity LUT looks perfect either way.
    for bi in range(SIZE):
        for gi in range(SIZE):
            for ri in range(SIZE):
                r, g, b = fn(ri / (SIZE - 1), gi / (SIZE - 1), bi / (SIZE - 1))
                lines.append(f"{r:.6f} {g:.6f} {b:.6f}")
    path = os.path.join(HERE, f"{name}.cube")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


if __name__ == "__main__":
    for look, fn in LOOKS.items():
        print("wrote", write_cube(look, fn))
